#!/bin/bash

BIRTHDAYS=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );
SRC="$BIRTHDAYS/src";
export COMMANDS="$SRC/commands";

source $SRC/function;

export BIRTHDAYS_FILE="birthdays.json";
export BIRTHDAYS_URL="$BIRTHDAYS/$BIRTHDAYS_FILE";
