import * as fs from "fs";
import { parse } from "csv-parse";
import { BirthDatabase } from "./structures/birth-database.js";

// environment variables generated by the setup bash script
export const fileName = process.env.BIRTHDAYS_FILE;
export const fileURL = process.env.BIRTHDAYS_URL;

// reads a .csv file to generate a database of birthdays
export async function createDatabase(file) {
  const birthdays = [];
  const database = new BirthDatabase();

  fs.createReadStream(file)
    .pipe(parse({ delimiter: ",", from_line: 2 }))
    .on("data", function (row) {
      birthdays.push(row);
    })
    .on("end", function () {
      database.build(birthdays);
      writeDatabase(database);
    })
    .on("error", function (error) {
      console.log(error.message);
    });
}

// writes to the database, using fileURL
export async function writeDatabase(database) {
  const res = JSON.stringify(database);
  fs.writeFile(fileURL, res, function (error, result) {
    if (error) {
      console.log(error.message);
    }
  });
}

// parses the JSON object database, and returns BirthDatabase
export async function readDatabase() {
  const res = JSON.parse(fs.readFileSync(fileURL));
  return await rebuildDatabase(res);
}

// with the JSON object, rebuilds the BirthDatabase object
export async function rebuildDatabase(database) {
  var res = new BirthDatabase();
  res.rebuild(database);
  return res;
}
